[package]
name = "rrun"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

which = "4.1.0"
serde_json = "1.0.64"
serde = { version = "1.0", features = ["derive"] }